### ISSUE TITLE
no code signature found

### ISSUE THREAD

**Issue by cuzv** [kokoabim/iOSOpenDev#142]
When run a Pod project with swift and obj-c framework on iPhone, will promote this error, Xcode 8.

**Comment by keshiim** [comment]
+1

**Comment by Liaojiahao** [comment]
+1

**Comment by JeffMv** [comment]
Did you set your apple *developer* account in the settings of Xcode ?
If you haven't, you have to set it : 
- Xcode 8    : https://i.stack.imgur.com/3Igsa.png
- Xcode < 8 : instead of [these values](http://devcenter.bitrise.io/img/ios/recommended-ios-code-signing-settings.png) put the ones related to your dev account.

Finally, if you played with some settings in SDKSettings.plist like in [this answer](http://stackoverflow.com/a/40587130), you may have to reinstall Xcode.

**Comment by cuzv** [comment]
@JeffMv Of course I set the developer account and enabled automatically manage signing, still not working.
Instead, I figured out another workaround by change the Podfile like this:
``` ruby
######## Target: XXXXX

def install_pods_by_objc
    # Objc
    pod 'Reveal-iOS-SDK', :configurations => ['Debug']
end

def install_pods_by_swift
    # Swift
    pod 'Alamofire'

    # Put follow lines in swift libs install command
    post_install do |installer|
        installer.pods_project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '3.0'
                config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = "iPhone Developer: Lethe Xiao (Q74F3EB3MU)"
                config.build_settings['CODE_SIGNING_REQUIRED'] = "YES"
                config.build_settings['CODE_SIGNING_ALLOWED'] = "YES"
            end
        end
    end

end

target 'XXXXX' do
    install_pods_by_objc
    install_pods_by_swift
end

```
